import { createClient } from '@supabase/supabase-js'

export const supabase = createClient('https://ebixepumsdzubodxrvsz.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImViaXhlcHVtc2R6dWJvZHhydnN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzMzA5NDUsImV4cCI6MjA1NjkwNjk0NX0.YinlAlZDaKlfMZDsqmNu3Wj9913Ld9Uda9ZYF1uaLYg')